
package com.sinosure.exchange.edi.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-07-15T18:18:39.472+08:00
 * Generated source version: 3.3.7
 */

@WebFault(name = "EdiException", targetNamespace = "http://service.edi.exchange.sinosure.com")
public class EdiException_Exception extends Exception {

    private com.sinosure.exchange.edi.service.EdiException ediException;

    public EdiException_Exception() {
        super();
    }

    public EdiException_Exception(String message) {
        super(message);
    }

    public EdiException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public EdiException_Exception(String message, com.sinosure.exchange.edi.service.EdiException ediException) {
        super(message);
        this.ediException = ediException;
    }

    public EdiException_Exception(String message, com.sinosure.exchange.edi.service.EdiException ediException, java.lang.Throwable cause) {
        super(message, cause);
        this.ediException = ediException;
    }

    public com.sinosure.exchange.edi.service.EdiException getFaultInfo() {
        return this.ediException;
    }
}
