package com.sinosure.exchange.edi.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-07-15T18:18:39.502+08:00
 * Generated source version: 3.3.7
 *
 */
@WebService(targetNamespace = "http://service.edi.exchange.sinosure.com", name = "SolEdiProxyWebServicePortType")
@XmlSeeAlso({ObjectFactory.class, com.sinosure.exchange.sedi3.po.ObjectFactory.class, com.sinosure.exchange.edi.po.ObjectFactory.class})
public interface SolEdiProxyWebServicePortType {

    @WebMethod(operationName = "EdiCheckAutoQuota")
    @RequestWrapper(localName = "EdiCheckAutoQuota", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.EdiCheckAutoQuota")
    @ResponseWrapper(localName = "EdiCheckAutoQuotaResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.EdiCheckAutoQuotaResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public java.lang.Double ediCheckAutoQuota(

        @WebParam(name = "corpSerialNo", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String corpSerialNo,
        @WebParam(name = "policyNo", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String policyNo,
        @WebParam(name = "buyerNo", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String buyerNo,
        @WebParam(name = "openBankSwift", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String openBankSwift,
        @WebParam(name = "exBankSwift", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String exBankSwift,
        @WebParam(name = "payMode", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String payMode,
        @WebParam(name = "payTerm", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.Long payTerm,
        @WebParam(name = "preTransporteDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar preTransporteDate,
        @WebParam(name = "insuranceRange", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.Long insuranceRange
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiLcQuotaApply", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiLcQuotaApply")
    @ResponseWrapper(localName = "doEdiLcQuotaApplyResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiLcQuotaApplyResponse")
    public void doEdiLcQuotaApply(

        @WebParam(name = "lcQuotaList", targetNamespace = "http://service.edi.exchange.sinosure.com")
        com.sinosure.exchange.edi.po.ArrayOfLcQuotaApplyInfo lcQuotaList
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiPolicyApply", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiPolicyApply")
    @ResponseWrapper(localName = "doEdiPolicyApplyResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiPolicyApplyResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.EdiFeedback doEdiPolicyApply(

        @WebParam(name = "policyApplyInfo", targetNamespace = "http://service.edi.exchange.sinosure.com")
        com.sinosure.exchange.edi.po.PolicyApplyInfo policyApplyInfo
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEdiDomPlNoticeApproveInfo", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiDomPlNoticeApproveInfo")
    @ResponseWrapper(localName = "getEdiDomPlNoticeApproveInfoResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiDomPlNoticeApproveInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfDomPlnoticeApproveInfo getEdiDomPlNoticeApproveInfo(

        @WebParam(name = "policyNo", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String policyNo,
        @WebParam(name = "startDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar endDate
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getSOLUserAuthorizationInfo", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetSOLUserAuthorizationInfo")
    @ResponseWrapper(localName = "getSOLUserAuthorizationInfoResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetSOLUserAuthorizationInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.SOLUserAuthorizationInfo getSOLUserAuthorizationInfo(

        @WebParam(name = "startdate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String startdate,
        @WebParam(name = "enddate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String enddate
    );

    @WebMethod
    @RequestWrapper(localName = "doEdiDomReceiptApply", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiDomReceiptApply")
    @ResponseWrapper(localName = "doEdiDomReceiptApplyResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiDomReceiptApplyResponse")
    public void doEdiDomReceiptApply(

        @WebParam(name = "domReceiptList", targetNamespace = "http://service.edi.exchange.sinosure.com")
        com.sinosure.exchange.edi.po.ArrayOfDomReceiptApplyInfo domReceiptList
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiShipmentApplyV2", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiShipmentApplyV2")
    @ResponseWrapper(localName = "doEdiShipmentApplyV2Response", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiShipmentApplyV2Response")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfEdiFeedback doEdiShipmentApplyV2(

        @WebParam(name = "shipmentList", targetNamespace = "http://service.edi.exchange.sinosure.com")
        com.sinosure.exchange.edi.po.ArrayOfShipmentApplyInfo shipmentList
    );

    @WebMethod(operationName = "doQuota_BackApply")
    @RequestWrapper(localName = "doQuota_BackApply", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoQuotaBackApply")
    @ResponseWrapper(localName = "doQuota_BackApplyResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoQuotaBackApplyResponse")
    public void doQuotaBackApply(

        @WebParam(name = "quotaApplyBackInfoList", targetNamespace = "http://service.edi.exchange.sinosure.com")
        com.sinosure.exchange.edi.po.ArrayOfQuotaApplyBackInfo quotaApplyBackInfoList
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiDocumentDownload", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiDocumentDownload")
    @ResponseWrapper(localName = "doEdiDocumentDownloadResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiDocumentDownloadResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public byte[] doEdiDocumentDownload(

        @WebParam(name = "docbillid", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String docbillid
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getQuotaBalanceInfo", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetQuotaBalanceInfo")
    @ResponseWrapper(localName = "getQuotaBalanceInfoResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetQuotaBalanceInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfQuotaBalanceInfo getQuotaBalanceInfo()
 throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiLcQuotaApplyV2", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiLcQuotaApplyV2")
    @ResponseWrapper(localName = "doEdiLcQuotaApplyV2Response", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiLcQuotaApplyV2Response")
    public void doEdiLcQuotaApplyV2(

        @WebParam(name = "lcQuotaList", targetNamespace = "http://service.edi.exchange.sinosure.com")
        com.sinosure.exchange.edi.po.ArrayOfLcQuotaApplyInfoV2 lcQuotaList
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiNoLcQuotaApply", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiNoLcQuotaApply")
    @ResponseWrapper(localName = "doEdiNoLcQuotaApplyResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiNoLcQuotaApplyResponse")
    public void doEdiNoLcQuotaApply(

        @WebParam(name = "noLcQuotaList", targetNamespace = "http://service.edi.exchange.sinosure.com")
        com.sinosure.exchange.edi.po.ArrayOfNoLcQuotaApplyInfo noLcQuotaList
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEdiFeeNoticeInfo", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiFeeNoticeInfo")
    @ResponseWrapper(localName = "getEdiFeeNoticeInfoResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiFeeNoticeInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfFeeNoticeInfo getEdiFeeNoticeInfo(

        @WebParam(name = "policyNo", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String policyNo,
        @WebParam(name = "startDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar endDate
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiReceiptAltApply", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiReceiptAltApply")
    @ResponseWrapper(localName = "doEdiReceiptAltApplyResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiReceiptAltApplyResponse")
    public void doEdiReceiptAltApply(

        @WebParam(name = "receiptAltList", targetNamespace = "http://service.edi.exchange.sinosure.com")
        com.sinosure.exchange.edi.po.ArrayOfReceiptAltApplyInfo receiptAltList
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEdiBasicFeeRate", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiBasicFeeRate")
    @ResponseWrapper(localName = "getEdiBasicFeeRateResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiBasicFeeRateResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfBasicFeeRate getEdiBasicFeeRate(

        @WebParam(name = "policyNo", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String policyNo,
        @WebParam(name = "startDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar endDate
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiBankCodeApprove", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiBankCodeApprove")
    @ResponseWrapper(localName = "doEdiBankCodeApproveResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiBankCodeApproveResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfBankCodeApproveInfo doEdiBankCodeApprove(

        @WebParam(name = "startDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar endDate
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEdiShipmentTotalApproveInfo", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiShipmentTotalApproveInfo")
    @ResponseWrapper(localName = "getEdiShipmentTotalApproveInfoResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiShipmentTotalApproveInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfShipmentTotalApproveInfo getEdiShipmentTotalApproveInfo(

        @WebParam(name = "policyNo", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String policyNo,
        @WebParam(name = "startDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar endDate
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEdiQuotaBackApproveInfo", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiQuotaBackApproveInfo")
    @ResponseWrapper(localName = "getEdiQuotaBackApproveInfoResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiQuotaBackApproveInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfQuotaBackApproveInfo getEdiQuotaBackApproveInfo(

        @WebParam(name = "policyNo", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String policyNo,
        @WebParam(name = "startDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar endDate
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEdiShipmentAlterApproveInfo", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiShipmentAlterApproveInfo")
    @ResponseWrapper(localName = "getEdiShipmentAlterApproveInfoResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiShipmentAlterApproveInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfShipmentAlterApproveInfo getEdiShipmentAlterApproveInfo(

        @WebParam(name = "policyNo", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String policyNo,
        @WebParam(name = "startDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar endDate
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEdiQuotaPreRevocationInfo", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiQuotaPreRevocationInfo")
    @ResponseWrapper(localName = "getEdiQuotaPreRevocationInfoResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiQuotaPreRevocationInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfQuotaPreRevocationInfo getEdiQuotaPreRevocationInfo(

        @WebParam(name = "policyNo", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String policyNo
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiFileUpload", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiFileUpload")
    @ResponseWrapper(localName = "doEdiFileUploadResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiFileUploadResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public java.lang.String doEdiFileUpload(

        @WebParam(name = "attaFile", targetNamespace = "http://service.edi.exchange.sinosure.com")
        com.sinosure.exchange.edi.po.ArrayOfAttafile attaFile
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEdiClaimApproveInfo", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiClaimApproveInfo")
    @ResponseWrapper(localName = "getEdiClaimApproveInfoResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiClaimApproveInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfClaimApproveInfo getEdiClaimApproveInfo(

        @WebParam(name = "policyNo", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String policyNo,
        @WebParam(name = "startDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String startDate,
        @WebParam(name = "endDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String endDate
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiShipmentApply", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiShipmentApply")
    @ResponseWrapper(localName = "doEdiShipmentApplyResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiShipmentApplyResponse")
    public void doEdiShipmentApply(

        @WebParam(name = "shipmentList", targetNamespace = "http://service.edi.exchange.sinosure.com")
        com.sinosure.exchange.edi.po.ArrayOfShipmentApplyInfo shipmentList
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEdiDomQuotaPreRevocationInfo", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiDomQuotaPreRevocationInfo")
    @ResponseWrapper(localName = "getEdiDomQuotaPreRevocationInfoResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiDomQuotaPreRevocationInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfDomQuotaPreRevocationInfo getEdiDomQuotaPreRevocationInfo(

        @WebParam(name = "policyNo", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String policyNo
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiPolicyConfirm", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiPolicyConfirm")
    @ResponseWrapper(localName = "doEdiPolicyConfirmResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiPolicyConfirmResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.EdiFeedback doEdiPolicyConfirm(

        @WebParam(name = "policyConfirmInfo", targetNamespace = "http://service.edi.exchange.sinosure.com")
        com.sinosure.exchange.edi.po.PolicyConfirmInfo policyConfirmInfo
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEdiQuotaapplys", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiQuotaapplys")
    @ResponseWrapper(localName = "getEdiQuotaapplysResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiQuotaapplysResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfQuotaInfo getEdiQuotaapplys(

        @WebParam(name = "clientno", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String clientno,
        @WebParam(name = "policyno", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String policyno,
        @WebParam(name = "startdate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar startdate,
        @WebParam(name = "enddate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar enddate,
        @WebParam(name = "quotastate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String quotastate
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEdiCreditReportApprove", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiCreditReportApprove")
    @ResponseWrapper(localName = "getEdiCreditReportApproveResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiCreditReportApproveResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfCreditReportApprove getEdiCreditReportApprove(

        @WebParam(name = "clientno", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String clientno,
        @WebParam(name = "startTime", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String startTime,
        @WebParam(name = "endTime", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String endTime
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEdiDomQuotaApproveInfo", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiDomQuotaApproveInfo")
    @ResponseWrapper(localName = "getEdiDomQuotaApproveInfoResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiDomQuotaApproveInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfDomQuotaApproveInfo getEdiDomQuotaApproveInfo(

        @WebParam(name = "policyNo", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String policyNo,
        @WebParam(name = "startDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar endDate
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiDomQuotaApply", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiDomQuotaApply")
    @ResponseWrapper(localName = "doEdiDomQuotaApplyResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiDomQuotaApplyResponse")
    public void doEdiDomQuotaApply(

        @WebParam(name = "domQuotaList", targetNamespace = "http://service.edi.exchange.sinosure.com")
        com.sinosure.exchange.edi.po.ArrayOfDomQuotaApplyInfo1 domQuotaList
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiShipmentTotalApply", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiShipmentTotalApply")
    @ResponseWrapper(localName = "doEdiShipmentTotalApplyResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiShipmentTotalApplyResponse")
    public void doEdiShipmentTotalApply(

        @WebParam(name = "contractApplyList", targetNamespace = "http://service.edi.exchange.sinosure.com")
        com.sinosure.exchange.edi.po.ArrayOfShipmentTotalApplyInfo contractApplyList
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEdiDomTotalDelcareApproveInfo", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiDomTotalDelcareApproveInfo")
    @ResponseWrapper(localName = "getEdiDomTotalDelcareApproveInfoResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiDomTotalDelcareApproveInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfDomTotalDeclareApproveInfo getEdiDomTotalDelcareApproveInfo(

        @WebParam(name = "policyNo", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String policyNo,
        @WebParam(name = "startDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String startDate,
        @WebParam(name = "endDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String endDate
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEdiContractApproveInfo", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiContractApproveInfo")
    @ResponseWrapper(localName = "getEdiContractApproveInfoResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiContractApproveInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfContractApproveInfo getEdiContractApproveInfo(

        @WebParam(name = "policyNo", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String policyNo,
        @WebParam(name = "startDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar endDate
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEdiPolicyApplyInfo", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiPolicyApplyInfo")
    @ResponseWrapper(localName = "getEdiPolicyApplyInfoResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiPolicyApplyInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.EdiPolicyInfo getEdiPolicyApplyInfo(

        @WebParam(name = "startdate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String startdate,
        @WebParam(name = "enddate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String enddate
    );

    @WebMethod
    @RequestWrapper(localName = "doEdiInfoAttachDownload", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiInfoAttachDownload")
    @ResponseWrapper(localName = "doEdiInfoAttachDownloadResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiInfoAttachDownloadResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public byte[] doEdiInfoAttachDownload(

        @WebParam(name = "attachID", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String attachID
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEdiReceiptApproveInfo", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiReceiptApproveInfo")
    @ResponseWrapper(localName = "getEdiReceiptApproveInfoResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiReceiptApproveInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfReceiptApproveInfo getEdiReceiptApproveInfo(

        @WebParam(name = "policyNo", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String policyNo,
        @WebParam(name = "startDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar endDate
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEdiShipmentApproveInfo", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiShipmentApproveInfo")
    @ResponseWrapper(localName = "getEdiShipmentApproveInfoResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiShipmentApproveInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfShipmentApproveInfo getEdiShipmentApproveInfo(

        @WebParam(name = "policyNo", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String policyNo,
        @WebParam(name = "startDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar endDate
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiInfoQuery", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiInfoQuery")
    @ResponseWrapper(localName = "doEdiInfoQueryResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiInfoQueryResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfEDIInfoStructure doEdiInfoQuery(

        @WebParam(name = "startDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String startDate,
        @WebParam(name = "endDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String endDate
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiAccountList", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiAccountList")
    @ResponseWrapper(localName = "doEdiAccountListResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiAccountListResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfAccount doEdiAccountList(

        @WebParam(name = "dealType", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String dealType
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEdiPlnoticeApproveInfo", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiPlnoticeApproveInfo")
    @ResponseWrapper(localName = "getEdiPlnoticeApproveInfoResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiPlnoticeApproveInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfPlnoticeApproveInfo getEdiPlnoticeApproveInfo(

        @WebParam(name = "policyNo", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String policyNo,
        @WebParam(name = "startDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar endDate
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiCreditReportInput", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiCreditReportInput")
    @ResponseWrapper(localName = "doEdiCreditReportInputResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiCreditReportInputResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfEdiFeedback doEdiCreditReportInput(

        @WebParam(name = "entrustInputList", targetNamespace = "http://service.edi.exchange.sinosure.com")
        com.sinosure.exchange.edi.po.ArrayOfEntrustInput entrustInputList
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEdiQuotaApproveInfo", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiQuotaApproveInfo")
    @ResponseWrapper(localName = "getEdiQuotaApproveInfoResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiQuotaApproveInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfQuotaApproveInfo getEdiQuotaApproveInfo(

        @WebParam(name = "policyNo", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String policyNo,
        @WebParam(name = "startDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar endDate
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getExchangeRate", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetExchangeRate")
    @ResponseWrapper(localName = "getExchangeRateResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetExchangeRateResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfCrediteExchangeRate getExchangeRate(

        @WebParam(name = "startDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar endDate,
        @WebParam(name = "moneyId", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String moneyId
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiPlnotice", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiPlnotice")
    @ResponseWrapper(localName = "doEdiPlnoticeResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiPlnoticeResponse")
    public void doEdiPlnotice(

        @WebParam(name = "plnoticeList", targetNamespace = "http://service.edi.exchange.sinosure.com")
        com.sinosure.exchange.edi.po.ArrayOfPlnotice plnoticeList
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEdiDomDeclareSupplementApproveInfo", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiDomDeclareSupplementApproveInfo")
    @ResponseWrapper(localName = "getEdiDomDeclareSupplementApproveInfoResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiDomDeclareSupplementApproveInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfDomDeclareSupplementApproveInfo getEdiDomDeclareSupplementApproveInfo(

        @WebParam(name = "policyNo", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String policyNo,
        @WebParam(name = "startDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar endDate
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiBuyerCodeApply", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiBuyerCodeApply")
    @ResponseWrapper(localName = "doEdiBuyerCodeApplyResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiBuyerCodeApplyResponse")
    public void doEdiBuyerCodeApply(

        @WebParam(name = "buyerCodeApplyInfoList", targetNamespace = "http://service.edi.exchange.sinosure.com")
        com.sinosure.exchange.edi.po.ArrayOfBuyerCodeApplyInfo buyerCodeApplyInfoList
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiShipmentAlterApply", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiShipmentAlterApply")
    @ResponseWrapper(localName = "doEdiShipmentAlterApplyResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiShipmentAlterApplyResponse")
    public void doEdiShipmentAlterApply(

        @WebParam(name = "shipmentAltList", targetNamespace = "http://service.edi.exchange.sinosure.com")
        com.sinosure.exchange.edi.po.ArrayOfShipmentAlterApplyInfo shipmentAltList
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getQuotaBalanceInfoByPolicyNo", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetQuotaBalanceInfoByPolicyNo")
    @ResponseWrapper(localName = "getQuotaBalanceInfoByPolicyNoResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetQuotaBalanceInfoByPolicyNoResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfQuotaBalanceInfo getQuotaBalanceInfoByPolicyNo(

        @WebParam(name = "policyNoList", targetNamespace = "http://service.edi.exchange.sinosure.com")
        com.sinosure.exchange.edi.service.ArrayOfString policyNoList
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiTotalDomDeclareApply", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiTotalDomDeclareApply")
    @ResponseWrapper(localName = "doEdiTotalDomDeclareApplyResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiTotalDomDeclareApplyResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfEdiFeedback doEdiTotalDomDeclareApply(

        @WebParam(name = "domTotalDeclareApplyInfoList", targetNamespace = "http://service.edi.exchange.sinosure.com")
        com.sinosure.exchange.edi.po.ArrayOfDomTotalDeclareApplyInfo domTotalDeclareApplyInfoList
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEdiSpecialFeeRate", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiSpecialFeeRate")
    @ResponseWrapper(localName = "getEdiSpecialFeeRateResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiSpecialFeeRateResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfSpecialFeeRate getEdiSpecialFeeRate(

        @WebParam(name = "policyNo", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String policyNo,
        @WebParam(name = "startDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar endDate
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiDomPlnotice", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiDomPlnotice")
    @ResponseWrapper(localName = "doEdiDomPlnoticeResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiDomPlnoticeResponse")
    public void doEdiDomPlnotice(

        @WebParam(name = "domPlnoticeList", targetNamespace = "http://service.edi.exchange.sinosure.com")
        com.sinosure.exchange.edi.po.ArrayOfDomPlNotice domPlnoticeList
    );

    @WebMethod
    @RequestWrapper(localName = "getEdiPolicyApproveInfo", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiPolicyApproveInfo")
    @ResponseWrapper(localName = "getEdiPolicyApproveInfoResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiPolicyApproveInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfEdiPolicyApproveInfo getEdiPolicyApproveInfo(

        @WebParam(name = "startDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String startDate,
        @WebParam(name = "endDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String endDate
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiReceiptApply", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiReceiptApply")
    @ResponseWrapper(localName = "doEdiReceiptApplyResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiReceiptApplyResponse")
    public void doEdiReceiptApply(

        @WebParam(name = "receiptList", targetNamespace = "http://service.edi.exchange.sinosure.com")
        com.sinosure.exchange.edi.po.ArrayOfReceiptApplyInfo receiptList
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiDomDeclareSupplementApply", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiDomDeclareSupplementApply")
    @ResponseWrapper(localName = "doEdiDomDeclareSupplementApplyResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiDomDeclareSupplementApplyResponse")
    public void doEdiDomDeclareSupplementApply(

        @WebParam(name = "domDeclareSupplementList", targetNamespace = "http://service.edi.exchange.sinosure.com")
        com.sinosure.exchange.edi.po.ArrayOfDomDeclareApplySupplementInfo domDeclareSupplementList
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEdiOverdueReceip", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiOverdueReceip")
    @ResponseWrapper(localName = "getEdiOverdueReceipResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiOverdueReceipResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfOverdueReceipt getEdiOverdueReceip(

        @WebParam(name = "corpSerialNo", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String corpSerialNo,
        @WebParam(name = "invoiceno", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String invoiceno,
        @WebParam(name = "buyerNo", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String buyerNo,
        @WebParam(name = "OverdueS", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String overdueS,
        @WebParam(name = "OverdueE", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String overdueE,
        @WebParam(name = "policyno", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String policyno
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiDomDeclareApply", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiDomDeclareApply")
    @ResponseWrapper(localName = "doEdiDomDeclareApplyResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiDomDeclareApplyResponse")
    public void doEdiDomDeclareApply(

        @WebParam(name = "domDeclareList", targetNamespace = "http://service.edi.exchange.sinosure.com")
        com.sinosure.exchange.edi.po.ArrayOfDomDeclareApplyInfo domDeclareList
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiNoLcQuotaApplyV2", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiNoLcQuotaApplyV2")
    @ResponseWrapper(localName = "doEdiNoLcQuotaApplyV2Response", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiNoLcQuotaApplyV2Response")
    public void doEdiNoLcQuotaApplyV2(

        @WebParam(name = "noLcQuotaList", targetNamespace = "http://service.edi.exchange.sinosure.com")
        com.sinosure.exchange.edi.po.ArrayOfNoLcQuotaApplyInfoV2 noLcQuotaList
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEdiDomReceiptApproveInfo", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiDomReceiptApproveInfo")
    @ResponseWrapper(localName = "getEdiDomReceiptApproveInfoResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiDomReceiptApproveInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfDomReceiptApproveInfo getEdiDomReceiptApproveInfo(

        @WebParam(name = "policyNo", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String policyNo,
        @WebParam(name = "startDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar endDate
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEdiSupplementDataApproveInfo", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiSupplementDataApproveInfo")
    @ResponseWrapper(localName = "getEdiSupplementDataApproveInfoResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiSupplementDataApproveInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfSupplementApproveInfo getEdiSupplementDataApproveInfo(

        @WebParam(name = "in0", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar in0,
        @WebParam(name = "in1", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar in1,
        @WebParam(name = "in2", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String in3
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiBuyerCodeApprove", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiBuyerCodeApprove")
    @ResponseWrapper(localName = "doEdiBuyerCodeApproveResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiBuyerCodeApproveResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfBuyerCodeApproveInfo doEdiBuyerCodeApprove(

        @WebParam(name = "startDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar endDate
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiInfoRetrieve", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiInfoRetrieve")
    @ResponseWrapper(localName = "doEdiInfoRetrieveResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiInfoRetrieveResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfInfoContents doEdiInfoRetrieve(

        @WebParam(name = "infoIDs", targetNamespace = "http://service.edi.exchange.sinosure.com")
        com.sinosure.exchange.edi.service.ArrayOfString infoIDs
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiContractApply", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiContractApply")
    @ResponseWrapper(localName = "doEdiContractApplyResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiContractApplyResponse")
    public void doEdiContractApply(

        @WebParam(name = "contractApplyList", targetNamespace = "http://service.edi.exchange.sinosure.com")
        com.sinosure.exchange.edi.po.ArrayOfContractApplyInfo contractApplyList
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEdiCountryClassify", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiCountryClassify")
    @ResponseWrapper(localName = "getEdiCountryClassifyResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiCountryClassifyResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfCountryClassify getEdiCountryClassify(

        @WebParam(name = "startDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar endDate
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiClaimApply", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiClaimApply")
    @ResponseWrapper(localName = "doEdiClaimApplyResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiClaimApplyResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfEdiFeedback doEdiClaimApply(

        @WebParam(name = "claimApplyList", targetNamespace = "http://service.edi.exchange.sinosure.com")
        com.sinosure.exchange.edi.po.ArrayOfClaimApply claimApplyList
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiDocumentList", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiDocumentList")
    @ResponseWrapper(localName = "doEdiDocumentListResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiDocumentListResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfDocumentInfo doEdiDocumentList(

        @WebParam(name = "startdate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar startdate,
        @WebParam(name = "enddate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar enddate,
        @WebParam(name = "doctype", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String doctype,
        @WebParam(name = "srccorpserialno", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String srccorpserialno
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiSupplementData", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiSupplementData")
    @ResponseWrapper(localName = "doEdiSupplementDataResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiSupplementDataResponse")
    public void doEdiSupplementData(

        @WebParam(name = "in0", targetNamespace = "http://service.edi.exchange.sinosure.com")
        com.sinosure.exchange.edi.po.ArrayOfSupplementInfo in0
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "doEdiBankCodeApply", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiBankCodeApply")
    @ResponseWrapper(localName = "doEdiBankCodeApplyResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.DoEdiBankCodeApplyResponse")
    public void doEdiBankCodeApply(

        @WebParam(name = "bankCodeApplyInfoList", targetNamespace = "http://service.edi.exchange.sinosure.com")
        com.sinosure.exchange.edi.po.ArrayOfBankCodeApplyInfo bankCodeApplyInfoList
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEdiDomDelcareApproveInfo", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiDomDelcareApproveInfo")
    @ResponseWrapper(localName = "getEdiDomDelcareApproveInfoResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiDomDelcareApproveInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfDomDeclareApproveInfo getEdiDomDelcareApproveInfo(

        @WebParam(name = "policyNo", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String policyNo,
        @WebParam(name = "startDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar endDate
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEdiCreditApplyInfo", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiCreditApplyInfo")
    @ResponseWrapper(localName = "getEdiCreditApplyInfoResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiCreditApplyInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.EdiRateInfo getEdiCreditApplyInfo(

        @WebParam(name = "startdate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String startdate,
        @WebParam(name = "enddate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String enddate
    );

    @WebMethod
    @RequestWrapper(localName = "getEdiRatingApproveInfo", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiRatingApproveInfo")
    @ResponseWrapper(localName = "getEdiRatingApproveInfoResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiRatingApproveInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfRatingInfo getEdiRatingApproveInfo(

        @WebParam(name = "buyerCode", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String buyerCode,
        @WebParam(name = "policyno", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String policyno,
        @WebParam(name = "startDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar endDate
    ) throws EdiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEdiReceiptAltApproveInfo", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiReceiptAltApproveInfo")
    @ResponseWrapper(localName = "getEdiReceiptAltApproveInfoResponse", targetNamespace = "http://service.edi.exchange.sinosure.com", className = "com.sinosure.exchange.edi.service.GetEdiReceiptAltApproveInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service.edi.exchange.sinosure.com")
    public com.sinosure.exchange.edi.po.ArrayOfReceiptAltApproveInfo getEdiReceiptAltApproveInfo(

        @WebParam(name = "PolicyNo", targetNamespace = "http://service.edi.exchange.sinosure.com")
        java.lang.String policyNo,
        @WebParam(name = "startDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://service.edi.exchange.sinosure.com")
        javax.xml.datatype.XMLGregorianCalendar endDate
    ) throws EdiException_Exception;
}
